### ISSUE TITLE
Docs or examples for creating custom prometheus metrics

### ISSUE THREAD

**Issue by starkers** [labstack/echo-contrib#76] opened 2022-05-18 19:01 UTC
### Issue Description

Hello, I'm just checking out the middleware (don't want to write my own)..

Typically I'm used to just using the vanilla prometheus `promauto` (EG `promauto.NewCounter()` to create custom metrics. However with this library and the [examples](https://echo.labstack.com/middleware/prometheus/#complex-scenarios) it is not clear how this is done with this middleware.

I can see severally public functions but honestly I can't figure out how to just do this simple thing.

Is this even possible? If so, I'm happy to PR some docs to echo with an example if someone can explain to me how to access them. (thanks)

### Checklist

- [x] Dependencies installed
- [x] No typos
- [x] Searched existing issues and docs

**Comment by thomasklein94** [comment] 2022-12-09 16:49
Hi @starkers,

I've just ran into this yesterday. I was able to figure it out (I think), and pushed a PR to the documentation [here](https://github.com/labstack/echox/pull/262).

**Comment by ankittiwari-harness** [comment] 2023-03-01 07:30
Hi @starkers I faced a similar issue and I was able to do it in a slightly different way.  As the issue is still open. adding the approach.

I initialised and registered my metrics prior to attaching the middleware and was able to add custom metrics in the platform.

Borrowing from the added doc above, it works in below format too

```
import "github.com/prometheus/client_golang/prometheus"

type Metrics struct {
	customCnt *prometheus.Metric
	customDur *prometheus.Metric
}

func NewMetrics() *Metrics {
	       customCnt: &prometheus.Metric{
			Name:        "custom_total",
			Description: "Custom counter events.",
			Type:        "counter_vec",
			Args:        []string{"label_one", "label_two"},
		},
		customDur: &prometheus.Metric{
			Name:        "custom_duration_seconds",
			Description: "Custom duration observations.",
			Type:        "histogram_vec",
			Args:        []string{"label_one", "label_two"},
			Buckets:     prom.DefBuckets, // or your Buckets
		},
	prometheus.MustRegister(customCnt, customDur, dequeueCounter)

        return &Metrics{customCnt:  customCnt, customDur: customDur}


}

```

Make sure the above code is invoked before your initializing echo server 


```
import 	"github.com/labstack/echo-contrib/prometheus"

func New(config *config.Config) *echo.Echo {

  e := echo.New()
  p := prometheus.NewPrometheus("echo", urlSkipperFunc)
  p.Use(e)
}
```

**Comment by aldas** [comment] 2023-05-23 20:36
closing, new middleware was added with #94


custom metrics can be added now as follows

NB: this example creates custom registry but you could register these also with default prometheus registry
```go
package main

import (
	"errors"
	"github.com/labstack/echo-contrib/echoprometheus"
	"github.com/labstack/echo/v4"
	"github.com/prometheus/client_golang/prometheus"
	"log"
	"net/http"
)

func main() {
	e := echo.New()

	customRegistry := prometheus.NewRegistry() // create custom registry for your custom metrics
	customCounter := prometheus.NewCounter(    // create new counter metric. This is replacement for `prometheus.Metric` struct
		prometheus.CounterOpts{
			Name: "custom_requests_total",
			Help: "How many HTTP requests processed, partitioned by status code and HTTP method.",
		},
	)
	if err := customRegistry.Register(customCounter); err != nil { // register your new counter metric with metrics registry
		log.Fatal(err)
	}

	e.Use(echoprometheus.NewMiddlewareWithConfig(echoprometheus.MiddlewareConfig{
		AfterNext: func(c echo.Context, err error) {
			customCounter.Inc() // use our custom metric in middleware. after every request increment the counter
		},
		Registerer: customRegistry, // use our custom registry instead of default Prometheus registry
	}))
	// register route for getting gathered metrics data from our custom Registry
	e.GET("/metrics", echoprometheus.NewHandlerWithConfig(echoprometheus.HandlerConfig{Gatherer: customRegistry})) 

	if err := e.Start(":8080"); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatal(err)
	}
}
```

**Closed by aldas** 2023-05-23 20:36 UTC
Labels: middleware|prometheus
