### ISSUE TITLE
Prometheus middleware generates new metrics for every 404

### ISSUE THREAD

**Issue by brietaylor** [labstack/echo-contrib#86] opened 2023-01-27 19:41 UTC
Every time a user requests a unique URL that returns 404, the Prometheus middleware generates new metrics.  This can easily generate millions of timeseries, overloading a Prometheus server or triggering other limits.

Minimal reproducer: https://gist.github.com/brietaylor/c5aa76df6a2f3fa3a8e14e4f8250cab1

Debugging:

I was able to trace this back through the code somewhat.  The code that generates these URLs ultimately traces back to `router.go:Find()` in Echo.  That code initially sets `Context.path` to the request path, but on all success paths, it overrides `Context.path` to the route path.  I couldn't find any way for middlewares to _detect_ which was done, though, so this might need to be an upstream fix.

https://github.com/labstack/echo/blob/master/router.go#L527

**Comment by brietaylor** [comment] 2023-01-27 19:54
I was able to trace this back through the code somewhat.  This middleware uses `Context.Path()` to generate URLs.

The code that generates these URLs ultimately traces back to `router.go:Find()` in Echo.  This code initially sets `Context.path` to the request path, but on all success paths, it overrides `Context.path` to the route path.  I couldn't find any way for middlewares to _detect_ which was done, though, so this might need to be an upstream fix.

https://github.com/labstack/echo/blob/master/router.go#L527

**Comment by lammel** [comment] 2023-02-20 09:36
We have been using our own metrics with a helper to discover the actual used route (the one configured in echo, not the actual path, so the list is not unbound) for a few years now.

Your proposed changes have been merged already with https://github.com/labstack/echo/pull/2385
So this will be resolved with the next minor release.

**Comment by aldas** [comment] 2023-03-03 10:09
Should be fixed. Please update Echo to latest version and this library to latest.

**Closed by aldas** 2023-03-03 10:09 UTC
Labels: middleware|prometheus

**Comment by therealak12** [comment] 2024-02-29 13:37
Hi.

Can you confirm the issue is resolved? @brietaylor 

I'm using echo v4.14.4 and echo-contrib v0.15.0. I still see new metrics for each new path with a 404 status code.
The solution is to make [this assignment](https://github.com/labstack/echo-contrib/blob/db8911a1af7abb6bdafbd999adada548fd9c0849/echoprometheus/prometheus.go#L270) conditional.

Here's [my proposed fix](https://github.com/labstack/echo-contrib/pull/111/files).
